### PR TITLE
create a responsive search bar component which renders search results based on filters and user typed data in the search bar

### PR DESCRIPTION
**Pull request by anjy7**
image
image

### CODE REVIEW

**Comment by Palanikannan1437** [comment]
@anjy7 Please add the autocomplete suggestions in the search bar and fetch the Markdown table data using a markdown to json parser from [this table](https://github.com/rohitg00/DevOpsCommunity#devops-resources)  instead of hardcoding it, thank you!

**Comment by anjy7** [comment]
image

**Comment by anjy7** [comment]
image
added dropdown which autocompletes the  suggestions in the search bar

**Comment by anjy7** [comment]
image

**Pull request merged**
